config/routes.rb
RailsInstallerDemo::Application.routes.draw do
  resources :users

  get "welcome/index"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  root :to => 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :gender, :image, :bio, :likes, :birthday, :location, :name, :oauth_expires_at, :oauth_token, :provider, :uid, :ProfilePicFullURL, :latitude, :longitude
	
	def self.from_omniauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
	    
	    logger.info 'TalkLocal: AuthInfo'
	    logger.info auth.to_yaml

	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.name = auth.info.name
	    user.email = auth.info.email
	    user.gender = auth.extra.raw_info.gender
	    user.image = auth.info.image
	    user.location = auth.info.location

	    user.oauth_token = auth.credentials.token
	    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	    user.save!

	    me = User.where(uid: user.uid)[0].facebook.get_object("me")
	    
	    logger.debug 'TalkLocal: Facebook::get_object("me")'
		logger.debug me.to_yaml

		user.bio = me["bio"]
		user.likes = me["likes"]
		user.birthday = me["birthday"]
	    user.save!

	    user.ProfilePicFullURL  = User.where(uid: user.uid)[0].facebook.get_picture("me", width: "320", height: "480")
	    user.save!

	  end
	end

	def facebook
		@facebook ||= Koala::Facebook::API.new(oauth_token)
		block_given? ? yield(@facebook) : @facebook
	rescue Koala::Facebook::APIError => e
		logger.info e.to_s
		nil	
	end

	def count_friends
		facebook { |fb| fb.get_connection("me", "friends").size }
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def me
  	@me ||= @current_user.facebook.get_object("me")
  end
  helper_method :me

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Talk Local Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%# csrf_meta_tags %>
</head>
<body>

	<div id="user_nav" align="right">
	  <% if current_user %>
	  	<%= image_tag(current_user.image) %>
		<strong><%= current_user.name %></strong> signed in! 
	    <%= link_to "Sign out", signout_path, id: "sign_out" %>
	  <% else %>
	    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
	  <% end %>
	</div>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_field :bio %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.text_field :birthday %>
  </div>
  <div class="field">
    <%= f.label :likes %><br />
    <%= f.text_field :likes %>
  </div>
  <div class="field">
    <%= f.label :oauth_token %><br />
    <%= f.text_field :oauth_token %>
  </div>
  <div class="field">
    <%= f.label :oauth_expires_at %><br />
    <%= f.datetime_select :oauth_expires_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Location</th>
    <th>Age</th>
    <th>Email</th>
    <th>Bio</th>
    <th>Likes</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to image_tag(user.image), user %></td>
    <td class='gender-<%=user.gender%>'> <%= user.name %> </td>
    <td> 
        <% if user.location and user.latitude and user.longitude %>  
        <%= link_to user.location, "http://maps.google.com/maps?q=#{user.latitude},#{user.longitude}", target: "_blank"  %>
        <% elsif user.latitude and user.longitude %>  
        <%= link_to "Map Coordinates", "http://maps.google.com/maps?q=#{user.latitude},#{user.longitude}", target: "_blank"  %>
        <% else %>
        <%= user.location %>
        <% end %>
    </td>
    <td><%= time_ago_in_words Date.strptime(user.birthday, "%m/%d/%Y") %></td>
    <td><%= link_to 'Email', 'mailto:' + user.email %></td>
    <td><%= user.bio %></td>
    <td><%= user.likes %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Provider:</b>
  <%= @user.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= @user.uid %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Gender:</b>
  <%= @user.gender %>
</p>

<p>
  <b>Image:</b>
  <% if @user.ProfilePicFullURL %>
  <%= image_tag(@user.ProfilePicFullURL) %>
  <% else %>
  <%= image_tag(@user.image) %>
  <% end %>
</p>

<p>
  <b>Location:</b>
  <% if @user.location and @user.latitude and @user.longitude %>  
  <%= link_to @user.location, "http://maps.google.com/maps?q=#{@user.latitude},#{@user.longitude}", target: "_blank"  %>
  <% elsif @user.latitude and @user.longitude %>  
  <%= link_to "Map Coordinates", "http://maps.google.com/maps?q=#{@user.latitude},#{@user.longitude}", target: "_blank"  %>
  <% else %>
  <%= @user.location %>
  <% end %>
</p>

<p>
  <b>Bio:</b>
  <%= @user.bio %>
</p>

<p>
  <b>Birthday:</b>
  <%= @user.birthday %>
</p>

<p>
  <b>Likes:</b>
  <%= @user.likes %>
</p>

<p>
  <b>Oauth token:</b>
  <%= @user.oauth_token %>
</p>

<p>
  <b>Oauth expires at:</b>
  <%= @user.oauth_expires_at %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Talk Local</h1>

<% if current_user %>
	Welcome <strong> <%= current_user.name %>! </strong> <br />
	<br />
	<%= link_to "View Users", users_path %> <br />
<% end %>